# Generated by Django 3.0.7 on 2020-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
